site_name: blindnet
site_url: https://docs.blindnet.io/
repo_url: https://github.com/blindnet-io/blindsend-be
repo_name: blindnet-docs
edit_uri: ""

copyright: Copyright &copy; 2021 blindnet

nav:
  - Quick start: quickstart.md
  - Guides:
    - Introduction: guides/introduction.md
    - Installation: guides/installation.md
    - Managing users and access: guides/managing_users_access.md
    - Encrypting data: guides/encrypt.md
    - Decrypting data: guides/decrypt.md
  - Api reference:
    - Api reference: api_reference/index.md
    - Client SDK:
      - JavaScript:
        - latest: api_reference/client/javascript/latest.md
        - v0.1.3: api_reference/client/javascript/0.1.3.md
    - Server SDK:
      - PHP:
        - latest: api_reference/server/php/latest.md
        - v0.9.2: api_reference/server/php/0.9.2.md
  - Troubleshooting:
    - Troubleshooting: troubleshooting/index.md
    - Error reference:
      - Client SDK:
        - JavaScript: troubleshooting/error_reference/client/javascript.md
  - Extra:
    - Glossary: other/glossary.md
    - Q&A: other/qna.md

extra:
  homepage: https://blindnet.io
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/blindnet_io
      name: blindnet on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/blindnet/
      name: blindnet on LinkedIn
    - icon: fontawesome/brands/medium
      link: https://medium.com/blindnet
      name: blindnet on Medium
    - icon: fontawesome/brands/github
      link: https://github.com/blindnet-io
      name: blindnet on Github
  generator: false

plugins:
  - search
  - localsearch

use_directory_urls: false

theme:
  name: material
  custom_dir: theme
  logo: img/favicon.ico
  favicon: img/favicon.ico
  font:
    text: Roboto

  features:
    - navigation.instant
    - navigation.expand
    - navigation.top
    # - header.autohide
    - navigation.tabs
    # this breaks the navigation for some reason
    # also back to top btn doesn't disappear when scrolled to the top 
    # - navigation.tabs.sticky
    - content.tabs.link
    - navigation.tracking
    - navigation.indexes
    - search.suggest
    - search.highlight
    # - navigation.sections
    # - toc.integrate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 1
      separator: "_"
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      linenums_style: table
      # linenums: true
  - pymdownx.inlinehilite
  # - pymdownx.highlight
  - pymdownx.tabbed
  - attr_list
  - footnotes